git-clone-dotfiles - fix fix fix

diff --git a/user/git-clone-dotfiles b/user/git-clone-dotfiles
--- a/user/git-clone-dotfiles
+++ b/user/git-clone-dotfiles
@@ -3,19 +3,16 @@
 # Be careful, this must not work well
 # even if there was already setup repo.
 
-# Clone dotfiles under this directory.
-DIR="$HOME/git"
-
 die() {
     echo "$@" >&2
     exit 1
 }
 
 
-mkdir -p $DIR
-cd $DIR || die "can't chdir to '$DIR'."
+cd $HOME/git || die "can't chdir to '$DIR'."
 
 if [ -d dotfiles ]; then
+    # Update only.
     cd dotfiles || die "can't chdir to 'dotfiles'."
     git pull origin master
     exit $?
@@ -27,20 +24,16 @@ cd dotfiles || die "can't chdir to 'dotfiles'.";
 git submodule update --init
 
 # Checkout HEAD branch.
-git submodule foreach 'git checkout master; true'
-# TODO: This will be changed in near future.
-(cd dotfiles/.vim/bundle/skk.vim && git checkout azik)
+git submodule foreach 'git checkout master; git pull origin master; true'
 
-git submodule foreach 'git pull origin master; true'
-
-# Create remote 'me', 'bare'.
+# Create remote 'me', 'backup'.
 git submodule foreach 'git remote add me git@github.com:tyru/`basename $path`.git; true'
-git submodule foreach 'git remote add bare ~/git/+public/github/`basename $path`.git; true'
-# Only './tools' has different name from github repo.
-# it is 'dotto'.
-(cd tools && {
-    git remote rm me;
-    git remote rm bare;
-    git remote add me git@github.com:tyru/dotto.git;
-    git remote add bare ~/git/+public/github/dotto.git;
-})
+git submodule foreach 'git remote add backup ~/git/+public/github/`basename $path`.git; true'
+# Only './tools' has different name (dotto) from github repo.
+doit() {
+    git remote rm me
+    git remote rm backup
+    git remote add me git@github.com:tyru/dotto.git
+    git remote add backup ~/git/+public/github/dotto.git
+}
+(cd tools && doit)
